# Generated by Django 4.1.5 on 2023-03-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='client',
        ),
    ]
