# Generated by Django 4.1.5 on 2023-04-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_address_client_company_website_client_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='image',
            new_name='company_image',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date_created',
            new_name='date_of_payment',
        ),
        migrations.AddField(
            model_name='client',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='current_monthly_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
