# Generated by Django 4.1.5 on 2023-04-03 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_clients_feedback_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients_feedback',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='clients_feedback',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='clients_feedback',
            name='preference',
        ),
        migrations.CreateModel(
            name='Clients_preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.TextField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Clients_General_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Clients_compaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compaints', to='client.client')),
            ],
        ),
    ]
