# Generated by Django 4.1.5 on 2023-04-03 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_clients_feedback_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_ID',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=50, null=True),
        ),
    ]
