# Generated by Django 4.1.5 on 2023-04-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_ID',
            field=models.AutoField(default=100100, primary_key=True, serialize=False),
        ),
    ]
