# Generated by Django 4.2.1 on 2023-05-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_payment_id_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_ID',
        ),
        migrations.AddField(
            model_name='client',
            name='product_category',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='product_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
