# Generated by Django 4.2.1 on 2023-06-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_remove_payment_product_remove_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_website',
            field=models.URLField(max_length=30, null=True),
        ),
    ]
